import { Geist, Geist_Mono } from 'next/font/google';
import Nav from "./components/Nav"
import { Inter } from 'next/font/google';
import './globals.css';


const geistSans = Geist({
  subsets: ['latin'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
};
const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className} ${geistMono.className} antialiased ${inter.className}`} suppressHydrationWarning>
         <Nav/>
        {children}
      </body>
    </html>
  );
}
